/* eslint-disable no-restricted-globals */

// Import Workbox libraries
import { precacheAndRoute } from 'workbox-precaching';

// Precache all the assets generated by the build process.
precacheAndRoute(self.__WB_MANIFEST);

// Cache-first strategy for all navigation requests (so the app works offline)
self.addEventListener('fetch', (event) => {
  if (event.request.mode === 'navigate') {
    event.respondWith(
      caches.match(event.request).then((cached) => {
        return cached || fetch(event.request);
      })
    );
  }
});

// Optional: Listen for the service worker's activation event to clean up old caches
self.addEventListener('activate', (event) => {
  const cacheWhitelist = ['version-1'];
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames.map((cacheName) => {
          if (!cacheWhitelist.includes(cacheName)) {
            // Return the cache deletion to fix the eslint warning
            return caches.delete(cacheName);
          }
          return null; // Add this return to ensure the map returns something in all cases
        })
      );
    })
  );
});
